version: '3.0'
services:
  rapilytics_service:
      image: rapilytics_service_image
      build:
        #specifiy the project build context
        context: .
        #specifiy the Dockerfile to use
        dockerfile: Dockerfile
      restart: always
      #bind host port 8989 to container port 8080
      ports:
         - 8989:80